apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: database
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: mysql-pod
          image: ECRURI/my-mysql-repo:v1.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always