apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
        - name: webapp-app
          image: 237049620366.dkr.ecr.us-east-1.amazonaws.com/my-webapp-repo:v1.0
          env:
            - name: DBHOST
              value: "sql-service.sql.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "pw"
            - name: APP_COLOR
              value: "blue"
          ports:
            - containerPort: 8080